const ActionTypes = Object.freeze({
    // auth
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    LOAD_USER: "LOAD_USER",
    AUTH_LOADING: "AUTH_LOADING",
    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",
    UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

    //notes
    FETCH_NOTES_REQUEST: 'FETCH_NOTES_REQUEST',
    FETCH_NOTES_SUCCESS: 'FETCH_NOTES_SUCCESS',
    FETCH_NOTES_FAILURE: 'FETCH_NOTES_FAILURE',

    ADD_NOTE_REQUEST: 'ADD_NOTE_REQUEST',
    ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
    ADD_NOTE_FAILURE: 'ADD_NOTE_FAILURE',

    DELETE_NOTE_REQUEST: 'DELETE_NOTE_REQUEST',
    DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS',
    DELETE_NOTE_FAILURE: 'DELETE_NOTE_FAILURE',

    UPDATE_NOTE_REQUEST: 'UPDATE_NOTE_REQUEST',
    UPDATE_NOTE_SUCCESS: 'UPDATE_NOTE_SUCCESS',
    UPDATE_NOTE_FAILURE: 'UPDATE_NOTE_FAILURE',

    // Task Boards
    FETCH_TASK_BOARDS_REQUEST: 'FETCH_TASK_BOARDS_REQUEST',
    FETCH_TASK_BOARDS_SUCCESS: 'FETCH_TASK_BOARDS_SUCCESS',
    FETCH_TASK_BOARDS_FAILURE: 'FETCH_TASK_BOARDS_FAILURE',

    FETCH_TASK_BOARD_REQUEST: 'FETCH_TASK_BOARD_REQUEST',
    FETCH_TASK_BOARD_SUCCESS: 'FETCH_TASK_BOARD_SUCCESS',
    FETCH_TASK_BOARD_FAILURE: 'FETCH_TASK_BOARD_FAILURE',

    CREATE_TASK_BOARD_REQUEST: 'CREATE_TASK_BOARD_REQUEST',
    CREATE_TASK_BOARD_SUCCESS: 'CREATE_TASK_BOARD_SUCCESS',
    CREATE_TASK_BOARD_FAILURE: 'CREATE_TASK_BOARD_FAILURE',

    UPDATE_TASK_BOARD_REQUEST: 'UPDATE_TASK_BOARD_REQUEST',
    UPDATE_TASK_BOARD_SUCCESS: 'UPDATE_TASK_BOARD_SUCCESS',
    UPDATE_TASK_BOARD_FAILURE: 'UPDATE_TASK_BOARD_FAILURE',

    DELETE_TASK_BOARD_REQUEST: 'DELETE_TASK_BOARD_REQUEST',
    DELETE_TASK_BOARD_SUCCESS: 'DELETE_TASK_BOARD_SUCCESS',
    DELETE_TASK_BOARD_FAILURE: 'DELETE_TASK_BOARD_FAILURE',

    CREATE_TASK_FUNNEL_REQUEST: 'CREATE_TASK_FUNNEL_REQUEST',
    CREATE_TASK_FUNNEL_SUCCESS: 'CREATE_TASK_FUNNEL_SUCCESS',
    CREATE_TASK_FUNNEL_FAILURE: 'CREATE_TASK_FUNNEL_FAILURE',

    UPDATE_TASK_FUNNEL_REQUEST: 'UPDATE_TASK_FUNNEL_REQUEST',
    UPDATE_TASK_FUNNEL_SUCCESS: 'UPDATE_TASK_FUNNEL_SUCCESS',
    UPDATE_TASK_FUNNEL_FAILURE: 'UPDATE_TASK_FUNNEL_FAILURE',

    DELETE_TASK_FUNNEL_REQUEST: 'DELETE_TASK_FUNNEL_REQUEST',
    DELETE_TASK_FUNNEL_SUCCESS: 'DELETE_TASK_FUNNEL_SUCCESS',
    DELETE_TASK_FUNNEL_FAILURE: 'DELETE_TASK_FUNNEL_FAILURE',

    REORDER_TASKS_REQUEST: 'REORDER_TASKS_REQUEST',
    REORDER_TASKS_SUCCESS: 'REORDER_TASKS_SUCCESS',
    REORDER_TASKS_FAILURE: 'REORDER_TASKS_FAILURE',

    // Tasks
    ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

    UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAILURE: 'UPDATE_TASK_FAILURE',

    UPDATE_TASK_STATUS_REQUEST: 'UPDATE_TASK_STATUS_REQUEST',
    UPDATE_TASK_STATUS_SUCCESS: 'UPDATE_TASK_STATUS_SUCCESS',
    UPDATE_TASK_STATUS_FAILURE: 'UPDATE_TASK_STATUS_FAILURE',

    // Finance categories
    FETCH_FINANCE_CATEGORIES_REQUEST: 'FETCH_FINANCE_CATEGORIES_REQUEST',
    FETCH_FINANCE_CATEGORIES_SUCCESS: 'FETCH_FINANCE_CATEGORIES_SUCCESS',
    FETCH_FINANCE_CATEGORIES_FAILURE: 'FETCH_FINANCE_CATEGORIES_FAILURE',

    CREATE_FINANCE_CATEGORY_REQUEST: 'CREATE_FINANCE_CATEGORY_REQUEST',
    CREATE_FINANCE_CATEGORY_SUCCESS: 'CREATE_FINANCE_CATEGORY_SUCCESS',
    CREATE_FINANCE_CATEGORY_FAILURE: 'CREATE_FINANCE_CATEGORY_FAILURE',

    UPDATE_FINANCE_CATEGORY_REQUEST: 'UPDATE_FINANCE_CATEGORY_REQUEST',
    UPDATE_FINANCE_CATEGORY_SUCCESS: 'UPDATE_FINANCE_CATEGORY_SUCCESS',
    UPDATE_FINANCE_CATEGORY_FAILURE: 'UPDATE_FINANCE_CATEGORY_FAILURE',

    DELETE_FINANCE_CATEGORY_REQUEST: 'DELETE_FINANCE_CATEGORY_REQUEST',
    DELETE_FINANCE_CATEGORY_SUCCESS: 'DELETE_FINANCE_CATEGORY_SUCCESS',
    DELETE_FINANCE_CATEGORY_FAILURE: 'DELETE_FINANCE_CATEGORY_FAILURE',

    // Finance transactions
    FETCH_FINANCE_TRANSACTIONS_REQUEST: 'FETCH_FINANCE_TRANSACTIONS_REQUEST',
    FETCH_FINANCE_TRANSACTIONS_SUCCESS: 'FETCH_FINANCE_TRANSACTIONS_SUCCESS',
    APPEND_FINANCE_TRANSACTIONS_SUCCESS: 'APPEND_FINANCE_TRANSACTIONS_SUCCESS',
    FETCH_FINANCE_TRANSACTIONS_FAILURE: 'FETCH_FINANCE_TRANSACTIONS_FAILURE',

    CREATE_FINANCE_TRANSACTION_REQUEST: 'CREATE_FINANCE_TRANSACTION_REQUEST',
    CREATE_FINANCE_TRANSACTION_SUCCESS: 'CREATE_FINANCE_TRANSACTION_SUCCESS',
    CREATE_FINANCE_TRANSACTION_FAILURE: 'CREATE_FINANCE_TRANSACTION_FAILURE',

    UPDATE_FINANCE_TRANSACTION_REQUEST: 'UPDATE_FINANCE_TRANSACTION_REQUEST',
    UPDATE_FINANCE_TRANSACTION_SUCCESS: 'UPDATE_FINANCE_TRANSACTION_SUCCESS',
    UPDATE_FINANCE_TRANSACTION_FAILURE: 'UPDATE_FINANCE_TRANSACTION_FAILURE',

    DELETE_FINANCE_TRANSACTION_REQUEST: 'DELETE_FINANCE_TRANSACTION_REQUEST',
    DELETE_FINANCE_TRANSACTION_SUCCESS: 'DELETE_FINANCE_TRANSACTION_SUCCESS',
    DELETE_FINANCE_TRANSACTION_FAILURE: 'DELETE_FINANCE_TRANSACTION_FAILURE',

    // Finance summary
    FETCH_FINANCE_MONTHLY_SUMMARY_REQUEST: 'FETCH_FINANCE_MONTHLY_SUMMARY_REQUEST',
    FETCH_FINANCE_MONTHLY_SUMMARY_SUCCESS: 'FETCH_FINANCE_MONTHLY_SUMMARY_SUCCESS',
    FETCH_FINANCE_MONTHLY_SUMMARY_FAILURE: 'FETCH_FINANCE_MONTHLY_SUMMARY_FAILURE',

    FETCH_FINANCE_CATEGORY_SUMMARY_REQUEST: 'FETCH_FINANCE_CATEGORY_SUMMARY_REQUEST',
    FETCH_FINANCE_CATEGORY_SUMMARY_SUCCESS: 'FETCH_FINANCE_CATEGORY_SUMMARY_SUCCESS',
    FETCH_FINANCE_CATEGORY_SUMMARY_FAILURE: 'FETCH_FINANCE_CATEGORY_SUMMARY_FAILURE',

    FETCH_FINANCE_RANGE_SUMMARY_REQUEST: 'FETCH_FINANCE_RANGE_SUMMARY_REQUEST',
    FETCH_FINANCE_RANGE_SUMMARY_SUCCESS: 'FETCH_FINANCE_RANGE_SUMMARY_SUCCESS',
    FETCH_FINANCE_RANGE_SUMMARY_FAILURE: 'FETCH_FINANCE_RANGE_SUMMARY_FAILURE',
});
export default ActionTypes;
